/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main (void)
{
  GtkWidget *main;
  GdkPixbuf *main_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *_1;
  GtkWidget *diff_tool;
  GtkWidget *_2;
  GtkWidget *diff3_tool;
  GtkWidget *alignment2;
  GtkWidget *checkbutton2;
  GtkWidget *hbuttonbox1;
  GtkWidget *_4;
  GtkWidget *_5;
  GtkWidget *_6;
  GtkWidget *_7;
  GtkWidget *hseparator1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main, "main");
  gtk_container_set_border_width (GTK_CONTAINER (main), 5);
  gtk_window_set_title (GTK_WINDOW (main), _("Xdiff-ext Setup"));
  gtk_window_set_position (GTK_WINDOW (main), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (main), TRUE);
  main_icon_pixbuf = create_pixbuf ("de.png");
  if (main_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main), main_icon_pixbuf);
      gdk_pixbuf_unref (main_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main), vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  _1 = gtk_label_new (_("Compare command:"));
  gtk_widget_set_name (_1, "_1");
  gtk_widget_show (_1);
  gtk_box_pack_start (GTK_BOX (vbox2), _1, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (_1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (_1), 4, 0);
  gtk_label_set_width_chars (GTK_LABEL (_1), 3);

  diff_tool = gtk_file_chooser_button_new (_("Select file comparison tool"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_set_name (diff_tool, "diff_tool");
  gtk_widget_show (diff_tool);
  gtk_box_pack_start (GTK_BOX (vbox2), diff_tool, FALSE, FALSE, 0);

  _2 = gtk_label_new (_("3-way compare command:"));
  gtk_widget_set_name (_2, "_2");
  gtk_widget_show (_2);
  gtk_box_pack_start (GTK_BOX (vbox2), _2, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (_2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (_2), 4, 0);
  gtk_label_set_width_chars (GTK_LABEL (_2), 3);

  diff3_tool = gtk_file_chooser_button_new (_("Select 3-way comparison tool"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_set_name (diff3_tool, "diff3_tool");
  gtk_widget_show (diff3_tool);
  gtk_box_pack_start (GTK_BOX (vbox2), diff3_tool, FALSE, FALSE, 0);

  alignment2 = gtk_alignment_new (0, 0.5, 0, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_box_pack_start (GTK_BOX (vbox2), alignment2, FALSE, TRUE, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("_keep files in list after comparison"));
  gtk_widget_set_name (checkbutton2, "checkbutton2");
  gtk_widget_show (checkbutton2);
  gtk_container_add (GTK_CONTAINER (alignment2), checkbutton2);
  gtk_tooltips_set_tip (tooltips, checkbutton2, _("Enable/disable 3-way compare"), NULL);
  gtk_widget_add_accelerator (checkbutton2, "activate", accel_group,
                              GDK_3, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (checkbutton2, "activate", accel_group,
                              GDK_3, (GdkModifierType) GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_end (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 11);

  _4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (_4, "_4");
  gtk_widget_show (_4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), _4);
  GTK_WIDGET_SET_FLAGS (_4, GTK_CAN_DEFAULT);

  _5 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (_5, "_5");
  gtk_widget_show (_5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), _5);
  GTK_WIDGET_SET_FLAGS (_5, GTK_CAN_DEFAULT);

  _6 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (_6, "_6");
  gtk_widget_show (_6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), _6);
  GTK_WIDGET_SET_FLAGS (_6, GTK_CAN_DEFAULT);

  _7 = gtk_button_new_from_stock ("gtk-about");
  gtk_widget_set_name (_7, "_7");
  gtk_widget_show (_7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), _7);
  GTK_WIDGET_SET_FLAGS (_7, GTK_CAN_DEFAULT);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 5);

  g_signal_connect ((gpointer) main, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) diff_tool, "selection_changed",
                    G_CALLBACK (on_diff_tool_selection_changed),
                    NULL);
  g_signal_connect ((gpointer) diff_tool, "realize",
                    G_CALLBACK (on_diff_tool_realize),
                    NULL);
  g_signal_connect ((gpointer) diff3_tool, "selection_changed",
                    G_CALLBACK (on_diff3_tool_selection_changed),
                    NULL);
  g_signal_connect ((gpointer) diff3_tool, "realize",
                    G_CALLBACK (on_diff3_tool_realize),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_keep_files_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "realize",
                    G_CALLBACK (on_keep_files_realize),
                    NULL);
  g_signal_connect ((gpointer) _4, "clicked",
                    G_CALLBACK (on_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) _5, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) _6, "clicked",
                    G_CALLBACK (on_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) _7, "clicked",
                    G_CALLBACK (on_about_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main, main, "main");
  GLADE_HOOKUP_OBJECT (main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main, _1, "_1");
  GLADE_HOOKUP_OBJECT (main, diff_tool, "diff_tool");
  GLADE_HOOKUP_OBJECT (main, _2, "_2");
  GLADE_HOOKUP_OBJECT (main, diff3_tool, "diff3_tool");
  GLADE_HOOKUP_OBJECT (main, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (main, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (main, _4, "_4");
  GLADE_HOOKUP_OBJECT (main, _5, "_5");
  GLADE_HOOKUP_OBJECT (main, _6, "_6");
  GLADE_HOOKUP_OBJECT (main, _7, "_7");
  GLADE_HOOKUP_OBJECT (main, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT_NO_REF (main, tooltips, "tooltips");

  gtk_widget_grab_default (_4);
  gtk_window_add_accel_group (GTK_WINDOW (main), accel_group);

  return main;
}

